CREATE TABLE IF NOT EXISTS tcpds_2_1_0.store_returns (
sr_returned_date_sk integer,
sr_return_time_sk integer,
sr_item_sk integer not null,
sr_customer_sk integer,
sr_cdemo_sk integer,
sr_hdemo_sk integer,
sr_addr_sk integer,
sr_store_sk integer,
sr_reason_sk integer,
sr_ticket_number integer not null,
sr_return_quantity integer,
sr_return_amt decimal(7,2),
sr_return_tax decimal(7,2),
sr_return_amt_inc_tax decimal(7,2),
sr_fee decimal(7,2),
sr_return_ship_cost decimal(7,2),
sr_refunded_cash decimal(7,2),
sr_reversed_charge decimal(7,2),
sr_store_credit decimal(7,2),
sr_net_loss decimal(7,2),
CONSTRAINT fk_sr_returned_date_sk FOREIGN KEY(sr_returned_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_sr_return_time_sk FOREIGN KEY(sr_return_time_sk) REFERENCES tcpds_2_1_0.time_dim(t_time_sk),
CONSTRAINT fk_sr_customer_sk FOREIGN KEY(sr_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_sr_cdemo_sk FOREIGN KEY(sr_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_sr_hdemo_sk FOREIGN KEY(sr_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_sr_addr_sk FOREIGN KEY(sr_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_sr_store_sk FOREIGN KEY(sr_store_sk) REFERENCES tcpds_2_1_0.store(s_store_sk),
CONSTRAINT fk_sr_reason_sk FOREIGN KEY(sr_reason_sk) REFERENCES tcpds_2_1_0.reason(r_reason_sk),
CONSTRAINT fk_pk FOREIGN KEY(sr_item_sk, sr_ticket_number) REFERENCES tcpds_2_1_0.store_sales(ss_item_sk, ss_ticket_number),
PRIMARY KEY (sr_item_sk, sr_ticket_number)
)