CREATE TABLE IF NOT EXISTS tcpds_2_1_0.household_demographics (
hd_demo_sk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
hd_income_band_sk integer,
hd_buy_potential char(15),
hd_dep_count integer,
hd_vehicle_count integer,
CONSTRAINT fk_hd_income_band_sk FOREIGN KEY(hd_income_band_sk) REFERENCES tcpds_2_1_0.income_band(ib_income_band_sk)
)