CREATE TABLE IF NOT EXISTS tcpds_2_1_0.web_page (
wp_web_page_sk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
wp_web_page_id char(16) NOT NULL,
wp_rec_start_date date,
wp_rec_end_date date,
wp_creation_date_sk integer,
wp_access_date_sk integer,
wp_autogen_flag char(1),
wp_customer_sk integer,
wp_url varchar(100),
wp_type char(50),
wp_char_count integer,
wp_link_count integer,
wp_image_count integer,
wp_max_ad_count integer,
CONSTRAINT fk_wp_creation_date_sk FOREIGN KEY(wp_creation_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_wp_access_date_sk FOREIGN KEY(wp_access_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_wp_customer_sk FOREIGN KEY(wp_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk)
)