CREATE TABLE IF NOT EXISTS tcpds_2_1_0.time_dim (
t_time_sk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
t_time_id char(16) NOT NULL,
t_time Integer,
t_hour Integer,
t_minute Integer,
t_second Integer,
t_am_pm char(2),
t_shift char(20),
t_sub_shift char(20),
t_meal_time char(20)
)