CREATE TABLE IF NOT EXISTS tcpds_2_1_0.catalog_sales (
cs_sold_date_sk integer,
cs_sold_time_sk integer,
cs_ship_date_sk integer,
cs_bill_customer_sk integer,
cs_bill_cdemo_sk integer,
cs_bill_hdemo_sk integer,
cs_bill_addr_sk integer,
cs_ship_customer_sk integer,
cs_ship_cdemo_sk integer,
cs_ship_hdemo_sk integer,
cs_ship_addr_sk integer,
cs_call_center_sk integer,
cs_catalog_page_sk integer,
cs_ship_mode_sk integer,
cs_warehouse_sk integer,
cs_item_sk integer not null,
cs_promo_sk integer,
cs_order_number integer not null,
cs_quantity integer,
cs_wholesale_cost decimal(7,2),
cs_list_price decimal(7,2),
cs_sales_price decimal(7,2),
cs_ext_discount_amt decimal(7,2),
cs_ext_sales_price decimal(7,2),
cs_ext_wholesale_cost decimal(7,2),
cs_ext_list_price decimal(7,2),
cs_ext_tax decimal(7,2),
cs_coupon_amt decimal(7,2),
cs_ext_ship_cost decimal(7,2),
cs_net_paid decimal(7,2),
cs_net_paid_inc_tax decimal(7,2),
cs_net_paid_inc_ship decimal(7,2),
cs_net_paid_inc_ship_tax decimal(7,2),
cs_net_profit decimal(7,2),
PRIMARY KEY (cs_item_sk, cs_order_number),
CONSTRAINT fk_cs_sold_date_sk FOREIGN KEY(cs_sold_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_cs_sold_time_sk FOREIGN KEY(cs_sold_time_sk) REFERENCES tcpds_2_1_0.time_dim(t_time_sk),
CONSTRAINT fk_cs_ship_date_sk FOREIGN KEY(cs_ship_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_cs_bill_customer_sk FOREIGN KEY(cs_bill_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_cs_bill_cdemo_sk FOREIGN KEY(cs_bill_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_cs_bill_hdemo_sk FOREIGN KEY(cs_bill_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_cs_bill_addr_sk FOREIGN KEY(cs_bill_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_cs_ship_customer_sk FOREIGN KEY(cs_ship_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_cs_ship_cdemo_sk FOREIGN KEY(cs_ship_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_cs_ship_hdemo_sk FOREIGN KEY(cs_ship_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_cs_ship_addr_sk FOREIGN KEY(cs_ship_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_cs_call_center_sk FOREIGN KEY(cs_call_center_sk) REFERENCES tcpds_2_1_0.call_center(cc_call_center_sk),
CONSTRAINT fk_cs_catalog_page_sk FOREIGN KEY(cs_catalog_page_sk) REFERENCES tcpds_2_1_0.catalog_page(cp_catalog_page_sk),
CONSTRAINT fk_cs_ship_mode_sk FOREIGN KEY(cs_ship_mode_sk) REFERENCES tcpds_2_1_0.ship_mode(sm_ship_mode_sk),
CONSTRAINT fk_cs_warehouse_sk FOREIGN KEY(cs_warehouse_sk) REFERENCES tcpds_2_1_0.warehouse(w_warehouse_sk),
CONSTRAINT fk_cs_item_sk FOREIGN KEY(cs_item_sk) REFERENCES tcpds_2_1_0.item(i_item_sk),
CONSTRAINT fk_cs_promo_sk FOREIGN KEY(cs_promo_sk) REFERENCES tcpds_2_1_0.promotion(p_promo_sk)
)