CREATE TABLE IF NOT EXISTS tcpds_2_1_0.customer_demographics (
cd_demo_sk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cd_gender char(1),
cd_marital_status char(1),
cd_education_status char(20),
cd_purchase_estimate integer,
cd_credit_rating char(10),
cd_dep_count integer,
cd_dep_employed_count integer,
cd_dep_college_count integer
)