CREATE TABLE IF NOT EXISTS tcpds_2_1_0.store_sales (
ss_sold_date_sk integer,
ss_sold_time_sk integer,
ss_item_sk integer,
ss_customer_sk integer,
ss_cdemo_sk integer,
ss_hdemo_sk integer,
ss_addr_sk integer,
ss_store_sk integer,
ss_promo_sk integer,
ss_ticket_number integer not null,
ss_quantity integer,
ss_wholesale_cost decimal(7,2),
ss_list_price decimal(7,2),
ss_sales_price decimal(7,2),
ss_ext_discount_amt decimal(7,2),
ss_ext_sales_price decimal(7,2),
ss_ext_wholesale_cost decimal(7,2),
ss_ext_list_price decimal(7,2),
ss_ext_tax decimal(7,2),
ss_coupon_amt decimal(7,2),
ss_net_paid decimal(7,2),
ss_net_paid_inc_tax decimal(7,2),
ss_net_profit decimal(7,2),
PRIMARY KEY (ss_item_sk, ss_ticket_number),
CONSTRAINT fk_ss_sold_date_sk FOREIGN KEY(ss_sold_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_ss_sold_time_sk FOREIGN KEY(ss_sold_time_sk) REFERENCES tcpds_2_1_0.time_dim(t_time_sk),
CONSTRAINT fk_ss_item_sk FOREIGN KEY(ss_item_sk) REFERENCES tcpds_2_1_0.item(i_item_sk),
CONSTRAINT fk_ss_customer_sk FOREIGN KEY(ss_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_ss_cdemo_sk FOREIGN KEY(ss_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_ss_hdemo_sk FOREIGN KEY(ss_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_ss_addr_sk FOREIGN KEY(ss_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_ss_store_sk FOREIGN KEY(ss_store_sk) REFERENCES tcpds_2_1_0.store(s_store_sk),
CONSTRAINT fk_ss_promo_sk FOREIGN KEY(ss_promo_sk) REFERENCES tcpds_2_1_0.promotion(p_promo_sk)
)