CREATE TABLE IF NOT EXISTS tcpds_2_1_0.web_returns (
wr_returned_date_sk integer,
wr_returned_time_sk integer,
wr_item_sk integer not null,
wr_refunded_customer_sk integer,
wr_refunded_cdemo_sk integer,
wr_refunded_hdemo_sk integer,
wr_refunded_addr_sk integer,
wr_returning_customer_sk integer,
wr_returning_cdemo_sk integer,
wr_returning_hdemo_sk integer,
wr_returning_addr_sk integer,
wr_web_page_sk integer,
wr_reason_sk integer,
wr_order_number integer not null,
wr_return_quantity integer,
wr_return_amt decimal(7,2),
wr_return_tax decimal(7,2),
wr_return_amt_inc_tax decimal(7,2),
wr_fee decimal(7,2),
wr_return_ship_cost decimal(7,2),
wr_refunded_cash decimal(7,2),
wr_reversed_charge decimal(7,2),
wr_account_credit decimal(7,2),
wr_net_loss decimal(7,2),
CONSTRAINT fk_wr_returned_date_sk FOREIGN KEY(wr_returned_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_wr_returned_time_sk  FOREIGN KEY(wr_returned_time_sk ) REFERENCES tcpds_2_1_0.time_dim(t_time_sk),
CONSTRAINT fk_wr_refunded_customer_sk FOREIGN KEY(wr_refunded_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_wr_refunded_cdemo_sk FOREIGN KEY(wr_refunded_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_wr_refunded_hdemo_sk FOREIGN KEY(wr_refunded_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_wr_refunded_addr_sk FOREIGN KEY(wr_refunded_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_wr_returning_customer_sk FOREIGN KEY(wr_returning_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_wr_returning_cdemo_sk FOREIGN KEY(wr_returning_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_wr_returning_hdemo_sk FOREIGN KEY(wr_returning_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_wr_returning_addr_sk FOREIGN KEY(wr_returning_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_wr_web_page_sk FOREIGN KEY(wr_web_page_sk) REFERENCES tcpds_2_1_0.web_page(wp_web_page_sk),
CONSTRAINT fk_wr_reason_sk FOREIGN KEY(wr_reason_sk) REFERENCES tcpds_2_1_0.reason(r_reason_sk),
CONSTRAINT fk_pk FOREIGN KEY(wr_item_sk, wr_order_number) REFERENCES tcpds_2_1_0.web_sales(ws_item_sk, ws_order_number),
PRIMARY KEY (wr_item_sk, wr_order_number)
)