CREATE TABLE IF NOT EXISTS tcpds_2_1_0.ship_mode (
sm_ship_mode_sk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
sm_ship_mode_id char(16) NOT NULL,
sm_type char(30),
sm_code char(10),
sm_carrier char(20),
sm_contract char(20)
)