CREATE TABLE IF NOT EXISTS tcpds_2_1_0.catalog_page (
cp_catalog_page_sk integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cp_catalog_page_id char(16) NOT NULL,
cp_start_date_sk integer,
cp_end_date_sk integer,
cp_department varchar(50),
cp_catalog_number integer,
cp_catalog_page_number integer,
cp_description varchar(100),
cp_type varchar(100),
CONSTRAINT fk_cp_start_date_sk FOREIGN KEY(cp_start_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_cp_end_date_sk FOREIGN KEY(cp_end_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk)
)