CREATE TABLE IF NOT EXISTS tcpds_2_1_0.catalog_returns (
cr_returned_date_sk integer,
cr_returned_time_sk integer,
cr_item_sk integer not null,
cr_refunded_customer_sk integer,
cr_refunded_cdemo_sk integer,
cr_refunded_hdemo_sk integer,
cr_refunded_addr_sk integer,
cr_returning_customer_sk integer,
cr_returning_cdemo_sk integer,
cr_returning_hdemo_sk integer,
cr_returning_addr_sk integer,
cr_call_center_sk integer,
cr_catalog_page_sk integer,
cr_ship_mode_sk integer,
cr_warehouse_sk integer,
cr_reason_sk integer,
cr_order_number integer not null,
cr_return_quantity integer,
cr_return_amount decimal(7,2),
cr_return_tax decimal(7,2),
cr_return_amt_inc_tax decimal(7,2),
cr_fee decimal(7,2),
cr_return_ship_cost decimal(7,2),
cr_refunded_cash decimal(7,2),
cr_reversed_charge decimal(7,2),
cr_store_credit decimal(7,2),
cr_net_loss decimal(7,2),
CONSTRAINT fk_cr_returned_date_sk FOREIGN KEY(cr_returned_date_sk) REFERENCES tcpds_2_1_0.date_dim(d_date_sk),
CONSTRAINT fk_cr_returned_time_sk  FOREIGN KEY(cr_returned_time_sk ) REFERENCES tcpds_2_1_0.time_dim(t_time_sk),
CONSTRAINT fk_cr_refunded_customer_sk FOREIGN KEY(cr_refunded_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_cr_refunded_cdemo_sk FOREIGN KEY(cr_refunded_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_cr_refunded_hdemo_sk FOREIGN KEY(cr_refunded_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_cr_refunded_addr_sk FOREIGN KEY(cr_refunded_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_cr_returning_customer_sk FOREIGN KEY(cr_returning_customer_sk) REFERENCES tcpds_2_1_0.customer(c_customer_sk),
CONSTRAINT fk_cr_returning_cdemo_sk FOREIGN KEY(cr_returning_cdemo_sk) REFERENCES tcpds_2_1_0.customer_demographics(cd_demo_sk),
CONSTRAINT fk_cr_returning_hdemo_sk FOREIGN KEY(cr_returning_hdemo_sk) REFERENCES tcpds_2_1_0.household_demographics(hd_demo_sk),
CONSTRAINT fk_cr_returning_addr_sk FOREIGN KEY(cr_returning_addr_sk) REFERENCES tcpds_2_1_0.customer_address(ca_address_sk),
CONSTRAINT fk_cr_call_center_sk FOREIGN KEY(cr_call_center_sk) REFERENCES tcpds_2_1_0.call_center(cc_call_center_sk),
CONSTRAINT fk_cr_catalog_page_sk FOREIGN KEY(cr_catalog_page_sk) REFERENCES tcpds_2_1_0.catalog_page(cp_catalog_page_sk),
CONSTRAINT fk_cr_ship_mode_sk FOREIGN KEY(cr_ship_mode_sk) REFERENCES tcpds_2_1_0.ship_mode(sm_ship_mode_sk),
CONSTRAINT fk_cr_warehouse_sk FOREIGN KEY(cr_warehouse_sk) REFERENCES tcpds_2_1_0.warehouse(w_warehouse_sk),
CONSTRAINT fk_cr_reason_sk FOREIGN KEY(cr_reason_sk) REFERENCES tcpds_2_1_0.reason(r_reason_sk),
CONSTRAINT fk_pk FOREIGN KEY(cr_item_sk, cr_order_number) REFERENCES tcpds_2_1_0.catalog_sales(cs_item_sk, cs_order_number),
PRIMARY KEY (cr_item_sk, cr_order_number)
)